#!/usr/bin/perl
##############################################################################
##
##  GREPW -- find set of words in a file or line(s)
##           this is parh of the TXFU collection of tools
##  2025-2026 (c) Vladi Belperchinov-Shabanski "Cade"
##                <cade@noxrun.com>
##          http://cade.noxrun.com
##
##  LICENSE: GPLv2
##
##############################################################################
use strict;

# fftwalk() is backported from Data::Tools module
use constant
{
    FFT_FILES  => 0x01,
    FFT_DIRS   => 0x02,

    FFT_SYMF   => 0x04, # allow symlink files in result (requires FFT_FILES)
    FFT_SYMD   => 0x08, # allow symlink dirs in result  (requires FFT_DIRS )

    FFT_FOLLOW => 0x10,
    FFT_DEBUG  => 0x80,

    FFT_ALL    => 0x01 | 0x02,
    FFT_ALLF   => 0x01 | 0x04,
    FFT_ALLD   => 0x02 | 0x08,
    FFT_ALL4   => 0x01 | 0x02 | 0x04 | 0x08,
    FFT_FULL   => 0x01 | 0x02 | 0x04 | 0x08 | 0x10,
};

our $HELP = <<END;
usage: $0 <options> word word(s) ... -- file file(s)...
options:
    -v        -- verbose, should be used first for full info
    -d        -- debug mode, multiple use is ok
    -r        -- recursive, traverse directories
    --        -- end of options and words, files and dirs follow
    -h        -- prints this help message
    --help    -- the same
notes:
  * search words and target files or directories are separated by "--"
  * words/files can be also separated by "+", "/", "---"
  * options cannot be grouped: -dr is invalid, correct is: -d -r
examples:
  grepw  power button  +  /etc/ /usr/etc/
  grepw  debug print   /  *.cpp *.h
END

my $opt_debug;
my $opt_dirs;
my $opt_verbose;

die $HELP unless @ARGV;

our @args;
our @arg_files;
while( @ARGV )
  {
  $_ = shift;
  if( /^(\/|\+|--+)$/io )
    {
    @arg_files = @ARGV;
    last;
    }
  if( /^-v/ )
    {
    $opt_verbose++;
    print "option: verbose\n";
    next;
    }
  if( /^-r/ )
    {
    $opt_dirs++;
    print "option: recursive\n" if $opt_verbose;
    next;
    }
  if( /^-d/ )
    {
    $opt_debug++;
    print "option: debug level increased to [$opt_debug]\n" if $opt_verbose;
    next;
    }
  if( /^(--?h(elp)?|help)$/io )
    {
    die $HELP;
    }
  push @args, $_;
  }

my @words = @args;

my @files;
for my $f ( @arg_files )
  {
  if( -d $f )
    {
    next unless $opt_dirs;
    my $fs = fftwalk( FFT_FILES | FFT_SYMF, "$f/." );
    push @files, @$fs;
    }
  else
    {
    push @files, $f;
    }
  }

find_words( \@words, $_ ) for @files;



sub find_words
{
  my $words = shift;
  my $fname = shift;

  open my $fi, '<', $fname;
  while( <$fi> )
    {
    chomp;
    return if /\000/; # skip binary files
    my $mc;
    for my $w ( @$words )
      {
      $mc++ if /$w/;
      }
    if( $mc == @$words )
      {
      print "$fname:$.\t$_\n";
      }
    }


}

##############################################################################
# fftwalk() is backported from Data::Tools module

sub __fftwalk
{
  my $e  = shift; # directory entry to traverse
  my $a  = shift; # results array ref
  my $ty = shift; # typemap, see FFTs above

  print "debug: __fftwalk [$e]\n" if $ty & FFT_DEBUG;

  opendir( my $dir, $e ) or return undef;
  my $ee;
  while( $ee = readdir $dir )
    {
    next if $ee eq '.' or $ee eq '..';
    my $eee = "$e/$ee";

    my $is_dir  = -d $eee;
    my $is_link = -l $eee;

    if( $is_dir )
      {
      push @$a, $eee if $is_link ? $ty & FFT_DIRS && $ty & FFT_SYMD : $ty & FFT_DIRS;
      __fftwalk( $eee, $a, $ty ) if ! $is_link or $ty & FFT_FOLLOW;
      }
    else
      {
      push @$a, $eee if $is_link ? $ty & FFT_FILES && $ty & FFT_SYMF : $ty & FFT_FILES;
      }
    }
  closedir( $dir );
}

# fast file tree walk
# * first argument is traversal typemap scalar or hash with options
# * rest of arguments are directory names to be walked
#
# examples:
#   my $res_arrref = fftwalk( FFT_FILES | FFT_SYMF, 'go', 'now/' );
#   fftwalk( { TYPE => FFT_FULL, ARRAY => \@res_arr }, 'go', 'now/' );
#
# options hash can have:
#   TYPE  => typemap
# this option tells which types of filesystem entries to be processed:
#   FFT_FILES  -- add found files
#   FFT_DIRS   -- add found directories
#   FFT_SYMF   -- add found file symlinks (needs FFT_FILES)
#   FFT_SYMD   -- add found dir  symlinks (needs FFT_DIRS )
#   FFT_FOLLOW -- follow/traverse symlink dirs
# there are few shortcut options (those above, combined):
#   FFT_ALL    -- all files and dirs but no symlinks
#   FFT_ALLF   -- all files and file symlinks
#   FFT_ALLD   -- all dirs  and  dir symlinks
#   FFT_ALL4   -- all files and dirs including symlinks
#   FFT_FULL   -- all files, dirs, symlinks and follow symlink dirs
# if TYPE is zero, fftwalk will not do anything
#   ARRAY => hashref_to_append_result_list

sub fftwalk
{
  my $ty = shift;

  my $opt = {};
  if( ref( $ty ) eq 'HASH' )
    {
    $opt = $ty;
    $ty = $opt->{ 'TYPE' };
    }
  else
    {
    $opt = {};
    }

  die "fftwalk() uses TYPE instead of MODE" if $opt->{ 'MODE' };

  my $a = $opt->{ 'ARRAY' } ? $opt->{ 'ARRAY' } : [];

  return $a unless $ty > 0; # do nothing if TYPE is zero

  __fftwalk( $_, $a, $ty ) for @_;
  return $a;
}

##############################################################################
