#!/usr/bin/perl
##############################################################################
##
##  PAVG -- find median number in a series of numbers
##          this is parh of the TXFU collection of tools
##
##  2025-2026 (c) Vladi Belperchinov-Shabanski "Cade"
##                <cade@noxrun.com>
##          http://cade.noxrun.com
##
##  LICENSE: GPLv2
##
##############################################################################
use strict;

my @its;
my $cnt;
my $all; # yes, I know $. :)

while(<>)
  {
  $all++;
  next unless /\d+/;
  chomp;
  push @its, $_;
  $cnt++;
  }

@its = sort { $a <=> $b } @its;
my $its = @its;
my $med = $its[$its/2];
my $min = $its[0];
my $max = $its[-1];

print "$med   $min   $max   $its   $all\n";
