#!/usr/bin/perl
##############################################################################
##
##  PWAKEHOST -- sends wakeonlan packet to wake a machine by MAC address
##          this is part of the TXFU collection of tools
##
##  2025-2026 (c) Vladi Belperchinov-Shabanski "Cade"
##                <cade@noxrun.com>
##          http://cade.noxrun.com
##
##  LICENSE: GPLv2
##
##############################################################################
use strict;
use Socket;

my $HELP = <<END;
usage: $0 MAC_ADDRESS [BROADCAST_IP] [PORT]

Sends a Wake-on-LAN "magic packet" to wake a machine by its MAC address.

arguments:
  MAC_ADDRESS   target hardware (MAC) address, 12 hex digits. any
                non-hex separators are ignored, so all of these forms
                are accepted and equivalent:
                    00:11:22:33:44:55   -- colon separated
                    00-11-22-33-44-55   -- dash separated
                    0011.2233.4455      -- dot separated (Cisco style)
                    001122334455        -- bare, no separators
  BROADCAST_IP  broadcast address to send the packet to
                (default 255.255.255.255)
  PORT          UDP port to send to (default 9)

examples:
  $0 00:11:22:33:44:55
  $0 00-11-22-33-44-55 192.168.0.255
  $0 001122334455 192.168.0.255 7
END

my $mac = $ARGV[0];
print( $HELP ), exit 0 if ! defined $mac or $mac =~ /^(--?h(elp)?|help)$/i;

my $host = $ARGV[1] || '255.255.255.255';
my $port = $ARGV[2] || 9;

$mac =~ s/[^0-9a-fA-F]//g;
xx( "invalid MAC [$mac]", 22 ) unless $mac =~ /^[0-9a-fA-F]{12}$/;

my $binmac;
$binmac .= chr(hex($_)) for $mac =~ /([0-9a-fA-F]{2})/g;

# Build packet: 0xFF x6 + MAC x16
my $packet = ( "\xFF" x 6 ) . ( $binmac x 16 );

# Send
socket( my $sock, PF_INET, SOCK_DGRAM, getprotobyname( 'udp' ) ) or xx( "socket: $!", 1 );
setsockopt( $sock, SOL_SOCKET, SO_BROADCAST, 1 ) or xx( "setsockopt: $!", 2 );
my $addr = inet_aton( $host ) or xx( "inet_aton: $host", 3 );
send( $sock, $packet, 0, pack( 'S n a4 x8', AF_INET, $port, $addr ) )  or xx( "send: $!", 4 );
close( $sock );

xx( "wake sent to $host:$port ($mac)", 0 );

sub xx
  {
  print STDERR shift(), "\n";
  exit shift();
  }

